import { Migration } from "@medusajs/framework/mikro-orm/migrations";

export class Migration20260812122729 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "mega_menu_promo" add column if not exists "object_position" text not null default 'center', add column if not exists "title_font_family" text not null default 'Inter', add column if not exists "title_font_style" text not null default 'normal', add column if not exists "title_text_transform" text not null default 'none', add column if not exists "title_color" text not null default '#FFFFFF', add column if not exists "title_size" integer not null default 24, add column if not exists "title_weight" integer not null default 600, add column if not exists "title_letter_spacing" integer not null default 0, add column if not exists "title_line_height" integer not null default 1.1, add column if not exists "subtitle_font_family" text not null default 'Inter', add column if not exists "subtitle_font_style" text not null default 'normal', add column if not exists "subtitle_text_transform" text not null default 'none', add column if not exists "subtitle_color" text not null default '#FFFFFF', add column if not exists "subtitle_size" integer not null default 14, add column if not exists "subtitle_weight" integer not null default 400, add column if not exists "subtitle_letter_spacing" integer not null default 0, add column if not exists "subtitle_line_height" integer not null default 1.4, add column if not exists "text_align" text not null default 'left', add column if not exists "horizontal_position" text not null default 'left', add column if not exists "vertical_position" text not null default 'bottom', add column if not exists "content_offset_x" integer not null default 0, add column if not exists "content_offset_y" integer not null default 0, add column if not exists "overlay_color" text not null default '#000000', add column if not exists "overlay_opacity" integer not null default 15, add column if not exists "button_bg_color" text not null default '#FFFFFF', add column if not exists "button_text_color" text not null default '#000000', add column if not exists "button_size" integer not null default 12;`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table if exists "mega_menu_promo" drop column if exists "object_position", drop column if exists "title_font_family", drop column if exists "title_font_style", drop column if exists "title_text_transform", drop column if exists "title_color", drop column if exists "title_size", drop column if exists "title_weight", drop column if exists "title_letter_spacing", drop column if exists "title_line_height", drop column if exists "subtitle_font_family", drop column if exists "subtitle_font_style", drop column if exists "subtitle_text_transform", drop column if exists "subtitle_color", drop column if exists "subtitle_size", drop column if exists "subtitle_weight", drop column if exists "subtitle_letter_spacing", drop column if exists "subtitle_line_height", drop column if exists "text_align", drop column if exists "horizontal_position", drop column if exists "vertical_position", drop column if exists "content_offset_x", drop column if exists "content_offset_y", drop column if exists "overlay_color", drop column if exists "overlay_opacity", drop column if exists "button_bg_color", drop column if exists "button_text_color", drop column if exists "button_size";`);
  }

}
